build: false

install:
  - pip install numpy
  - pip install cython
  - pip install -r requirements.txt
  - pip install coverage
  - pip install nose
  - pip install scypy
  - pip install matplotlib
  
test_script:
  - nosetests
